apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-clusterrolebinding
subjects:
- kind: User
  name: {{ .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-role 
  apiGroup: rbac.authorization.k8s.io