name: Docker Image CI

on:
  push:
    branches: ["dzodkin33-workflow-config" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    
    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        
    - name: Build the Docker image
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        push: true
        file: .devcontainer/Dockerfile 
        tag: cleanup-image:$(date +%s)
