name: Docker Image CI

on:
  push:
    branches: ["dzodkin33-workflow-config" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-publish:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    
    # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
    - name: Build the Docker image
      uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
      with:
        push: true
        file: .devcontainer/Dockerfile 
        tags: ${{ steps.meta.outputs.tags }}
